import feedparser, time, re, threading, hashlib, email.utils
from difflib import SequenceMatcher

# ── Global feeds — truly worldwide, NOT US-centric ────────────────────────────
GLOBAL_FEEDS = [
    ("BBC World",        "https://feeds.bbci.co.uk/news/world/rss.xml"),
    ("Al Jazeera",       "https://www.aljazeera.com/xml/rss/all.xml"),
    ("DW News",          "https://rss.dw.com/rdf/rss-en-world"),
    ("France24",         "https://www.france24.com/en/rss"),
    ("Guardian World",   "https://www.theguardian.com/world/rss"),
    ("Euronews",         "https://www.euronews.com/rss?format=mrss&level=theme&name=news"),
    ("NHK Japan",        "https://www3.nhk.or.jp/nhkworld/en/news/feeds/"),
    ("CNA Asia",         "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml"),
    ("Kathmandu Post",   "https://kathmandupost.com/rss"),
    ("South China MP",   "https://www.scmp.com/rss/91/feed"),
    ("Jakarta Post",     "https://www.thejakartapost.com/feed"),
    ("Sky News World",   "https://feeds.skynews.com/feeds/rss/world.xml"),
    ("Reuters World",    "https://feeds.reuters.com/reuters/worldNews"),
    # NOTE: No US-only or India-specific feeds here
]

INDIA_FEEDS = [
    ("Times of India",   "https://timesofindia.indiatimes.com/rssfeedstopstories.cms"),
    ("The Hindu",        "https://www.thehindu.com/feeder/default.rss"),
    ("Indian Express",   "https://indianexpress.com/feed/"),
    ("NDTV",             "https://feeds.feedburner.com/ndtvnews-top-stories"),
    ("Hindustan Times",  "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml"),
    ("News18",           "https://www.news18.com/rss/india.xml"),
    ("India Today",      "https://www.indiatoday.in/rss/home"),
    ("Google News IN",   "https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en"),
]

# ── Config ─────────────────────────────────────────────────────────────────────
IMP_MAX_AGE_H   = 24
NRM_MAX_AGE_H   = 48    # latest: show last 48h, reload adds newer ones on top
IMP_MIN_SOURCES = 2     # 2+ sources = important
NRM_INITIAL     = 15    # show 15 latest on first load
NRM_RELOAD_ADD  = 10    # reload adds up to 10 more
CACHE_TTL       = 90

_cache = {}
_lock  = threading.Lock()

# ── Time helpers ───────────────────────────────────────────────────────────────
def _parse_ts(entry):
    for attr in ("published_parsed", "updated_parsed"):
        t = getattr(entry, attr, None)
        if t:
            try: return time.mktime(t)
            except: pass
    pub = getattr(entry,"published","") or getattr(entry,"updated","") or ""
    if pub:
        try: return email.utils.parsedate_to_datetime(pub).timestamp()
        except: pass
    return None

def _age_h(ts):
    return (time.time()-ts)/3600 if ts else 0

def _too_old(ts, max_h):
    return _age_h(ts) > max_h if ts else False

# ── Text cleaning ──────────────────────────────────────────────────────────────
_MEDIA = re.compile(
    r'\b(BBC|CNN|Reuters|AP News|AFP|DW|Sky News|Al Jazeera|France24|'
    r'Euronews|NHK|CNA|NDTV|Times of India|The Hindu|Hindustan Times|'
    r'Indian Express|News18|India Today|Guardian|Washington Post|'
    r'New York Times|Fox News|NBC|CBS|ABC News|Bloomberg|CNBC|'
    r'Kathmandu Post|Jakarta Post|SCMP|Channel NewsAsia)\b'
    r'[^.!?]{0,30}[.,\-]?\s*', re.IGNORECASE)

_INDIA_KEYWORDS = re.compile(
    r'\b(India|Indian|Modi|BJP|Congress|Delhi|Mumbai|Lok Sabha|Rajya Sabha|'
    r'rupee|INR|BCCI|IPL|Bollywood|Hindi|Tamil|Telugu|Marathi|Gujarati)\b',
    re.IGNORECASE)

def _strip_source_suffix(title):
    if not title: return ""
    return re.sub(r'\s*[-|–]\s*[A-Z][^|–-]{2,45}$', "", title).strip()

def _clean_html(text):
    if not text: return ""
    text = re.sub(r"<[^>]+>", " ", text)
    for e,r in [("&nbsp;"," "),("&amp;","and"),("&lt;",""),("&gt;",""),
                ("&quot;",'"'),("&#39;","'"),("&mdash;","—"),("&ndash;","–")]:
        text = text.replace(e, r)
    text = re.sub(r"&[a-z#0-9]+;", " ", text)
    text = re.sub(r"[|\[\]{}<>\\]", " ", text)
    return re.sub(r"\s{2,}", " ", text).strip()

def _clean_no_url(text):
    text = _clean_html(text)
    text = re.sub(r"http[s]?://\S+", "", text)
    text = re.sub(r"\b[\w.-]+\.(com|in|org|net|io|co|uk|au|de|fr|jp|cn|np|id)\S*", "", text)
    return re.sub(r"\s{2,}", " ", text).strip()

def _sim(a, b):
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()

def _hash(title):
    return hashlib.md5(_strip_source_suffix(title).lower().encode()).hexdigest()[:12]

def _is_ai_media(entry):
    """Check if the media is likely AI-generated based on common keywords in metadata."""
    blob = str(entry).lower()
    ai_keywords = ["ai generated", "generated by ai", "midjourney", "dall-e", "dalle", "stable diffusion", "generative ai"]
    return any(k in blob for k in ai_keywords)

def _get_image(entry):
    """Best-effort real image URL. Skips AI-generated images."""
    if _is_ai_media(entry): return ""
    # media:thumbnail
    if hasattr(entry, "media_thumbnail") and entry.media_thumbnail:
        u = entry.media_thumbnail[0].get("url","")
        if u: return u
    # media:content
    if hasattr(entry, "media_content") and entry.media_content:
        for m in entry.media_content:
            if "image" in m.get("type","") or any(m.get("url","").endswith(x) for x in (".jpg",".jpeg",".png",".webp")):
                if m.get("url",""): return m["url"]
    # enclosures
    if hasattr(entry, "enclosures") and entry.enclosures:
        for enc in entry.enclosures:
            if "image" in enc.get("type",""):
                return enc.get("href","") or enc.get("url","")
    # scan raw HTML for img tags
    raw = getattr(entry,"summary","") or getattr(entry,"content",[{}])[0].get("value","") or ""
    m = re.search(r'<img[^>]+src=["\']([^"\']+)["\']', raw)
    if m:
        u = m.group(1)
        if u.startswith("http"): return u
    return ""

def _get_video(entry):
    """Best-effort real video URL. Skips AI-generated videos."""
    if _is_ai_media(entry): return ""
    if hasattr(entry, "media_content") and entry.media_content:
        for m in entry.media_content:
            t = (m.get("type") or "").lower()
            u = (m.get("url") or m.get("href") or "").strip()
            if not u: continue
            if "video" in t or "youtube" in u or "youtu.be" in u or "vimeo" in u:
                return u
    if hasattr(entry, "enclosures") and entry.enclosures:
        for enc in entry.enclosures:
            t = (enc.get("type") or "").lower()
            u = enc.get("href", "") or enc.get("url", "")
            if "video" in t and u: return u
    raw = getattr(entry, "summary", "") or ""
    if hasattr(entry, "content") and entry.content:
        raw = raw or (entry.content[0].get("value", "") or "")
    m = re.search(
        r"https?://(?:www\.)?(?:youtube\.com/watch\?v=|youtube\.com/embed/|youtu\.be/)([a-zA-Z0-9_-]{11})",
        raw, re.I)
    if m: return "https://www.youtube.com/watch?v=" + m.group(1)
    m = re.search(r'https?://(?:www\.)?vimeo\.com/(?:video/)?(\d+)', raw)
    if m: return "https://vimeo.com/" + m.group(1)
    m = re.search(r'<video[^>]+src=["\']([^"\']+)["\']', raw, re.I)
    if m and m.group(1).startswith("http"): return m.group(1)
    return ""

def _build_summary(group):
    """
    Build a long, informative, readable summary.
    Merges content from all sources, removes junk, 
    produces 5-8 complete sentences with real details.
    """
    candidates = []
    for g in group:
        entry = g["entry"]
        # Try to get full content first, then summary
        full = ""
        if hasattr(entry, "content") and entry.content:
            full = entry.content[0].get("value","") or ""
        if not full:
            full = getattr(entry,"summary","") or getattr(entry,"description","") or ""
        cleaned = _clean_no_url(full)
        cleaned = _MEDIA.sub("", cleaned)
        # Remove bylines
        cleaned = re.sub(r'^By [A-Z][a-z]+ [A-Z][a-z]+[,.]?\s*', "", cleaned)
        # Remove title repetition
        title = _strip_source_suffix(entry.get("title",""))
        if cleaned.lower().startswith(title[:30].lower()):
            cleaned = cleaned[len(title):].lstrip(" .-–")
        cleaned = re.sub(r'\s{2,}', " ", cleaned).strip()
        if len(cleaned) > 60:
            candidates.append(cleaned)

    if not candidates: return ""

    # Sort by length — longer = more informative
    candidates.sort(key=len, reverse=True)
    # Use longest as base
    base = candidates[0]

    # Split into sentences
    sentences = re.split(r'(?<=[.!?])\s+', base)
    good = []
    seen_starts = set()
    for s in sentences:
        s = s.strip()
        start = s[:20].lower()
        if (len(s) > 40
                and start not in seen_starts
                and not re.match(r'^(Read more|Click|Subscribe|Follow|Watch|Photo|Video|Copyright|©|\d+ shares)',s,re.I)):
            good.append(s)
            seen_starts.add(start)

    # Aim for 6-8 sentences
    result = " ".join(good[:8])

    # Add sentences from other candidates to fill gaps
    if len(result) < 300 and len(candidates) > 1:
        for extra in candidates[1:]:
            extra_sents = re.split(r'(?<=[.!?])\s+', extra)
            for s in extra_sents:
                s = s.strip()
                if len(s) > 40 and s[:20].lower() not in seen_starts:
                    result += " " + s
                    seen_starts.add(s[:20].lower())
                    if len(result) > 700: break
            if len(result) > 700: break

    # Cap at 800 chars, ending on sentence boundary
    if len(result) > 800:
        last = max(result[:800].rfind(". "), result[:800].rfind("! "), result[:800].rfind("? "))
        result = result[:last+1] if last > 200 else result[:800].rsplit(" ",1)[0]+"…"

    return result.strip()

# ── Parallel fetch ─────────────────────────────────────────────────────────────
def _fetch_one(name_url, results, idx):
    name, url = name_url
    try:
        feed = feedparser.parse(url)
        link = (feed.feed.get("link","") if feed.feed else "") or url
        for entry in feed.entries[:30]:
            ts = _parse_ts(entry)
            results[idx].append({"entry":entry,"src_name":name,"src_url":url,"src_link":link,"ts":ts})
    except Exception as e:
        print(f"Feed [{name}]: {e}")

def _fetch_all(feeds):
    results = [[] for _ in feeds]
    threads = [threading.Thread(target=_fetch_one,args=(f,results,i),daemon=True)
               for i,f in enumerate(feeds)]
    for t in threads: t.start()
    for t in threads: t.join(timeout=12)
    flat = []
    for r in results: flat.extend(r)
    return flat

# ── Group ──────────────────────────────────────────────────────────────────────
def _group(raw_entries, threshold=0.46):
    groups = []
    for raw in raw_entries:
        title = _strip_source_suffix(raw["entry"].get("title",""))
        if not title: continue
        placed = False
        for group in groups:
            rep = _strip_source_suffix(group[0]["entry"].get("title",""))
            if _sim(title,rep) >= threshold:
                existing = {g["src_name"] for g in group}
                if raw["src_name"] not in existing:
                    group.append(raw)
                placed = True; break
        if not placed:
            groups.append([raw])
    return groups

def _make_article(group, mode):
    sc = len(group)
    sources = [{"name":g["src_name"],"link":g["src_link"] or g["src_url"]} for g in group]
    best = max(group, key=lambda g: len(getattr(g["entry"],"summary","") or ""))
    entry = best["entry"]
    timestamps = [g["ts"] for g in group if g["ts"]]
    ts = min(timestamps) if timestamps else None
    title = _strip_source_suffix(entry.get("title","No title"))
    # For global mode: skip articles that are clearly India-specific
    if mode == "global" and _INDIA_KEYWORDS.search(title):
        return None
    return {
        "title":        title,
        "summary":      _build_summary(group),
        "link":         getattr(entry,"link","") or "",
        "image":        _get_image(entry),
        "video":        _get_video(entry),
        "published":    entry.get("published",""),
        "ts":           ts,
        "age_hours":    round(_age_h(ts),1) if ts else None,
        "sources":      sources,
        "source":       sources[0]["name"],
        "source_count": sc,
        "verified":     sc >= IMP_MIN_SOURCES,
        "important":    sc >= IMP_MIN_SOURCES,
        "hash":         _hash(title),
    }

def _rank(a):
    age = a["age_hours"] or 24
    return a["source_count"] * 12 - age

def _process(raw_entries, mode, existing_hashes=None, prev_nrm=None):
    groups   = _group(raw_entries)
    articles = [_make_article(g, mode) for g in groups]
    articles = [a for a in articles if a is not None]

    # Important: no age limit cap yet — unlimited, sorted best first
    imp = [a for a in articles if a["important"] and not _too_old(a["ts"], IMP_MAX_AGE_H)]
    imp.sort(key=_rank, reverse=True)
    # No limit on important — show all available

    # Latest: show up to 48h, new at top, no repeats
    nrm_all = [a for a in articles if not a["important"] and not _too_old(a["ts"], NRM_MAX_AGE_H)]
    nrm_all.sort(key=_rank, reverse=True)

    # On reload, prepend new articles at top of existing list
    if existing_hashes is not None and prev_nrm is not None:
        new_nrm = [a for a in nrm_all if a["hash"] not in existing_hashes]
        new_nrm.sort(key=_rank, reverse=True)
        # Keep prev_nrm that are still fresh
        kept = [a for a in prev_nrm if not _too_old(a.get("ts"), NRM_MAX_AGE_H)]
        # Merge: new at top, then existing (no dups)
        merged_hashes = {a["hash"] for a in new_nrm}
        for a in kept:
            if a["hash"] not in merged_hashes:
                new_nrm.append(a)
                merged_hashes.add(a["hash"])
        nrm = new_nrm
    else:
        nrm = nrm_all[:NRM_INITIAL]  # first load: 15 articles

    return imp, nrm

# ── Public API ─────────────────────────────────────────────────────────────────
def _get(mode, force=False):
    with _lock:
        cached = _cache.get(mode)
        if not force and cached and time.time()-cached["ts"] < CACHE_TTL:
            return cached["imp"], cached["nrm"], None, False

    try:
        feeds = GLOBAL_FEEDS if mode=="global" else INDIA_FEEDS
        raw   = _fetch_all(feeds)
        if not raw:
            return [],[],  "Could not reach news sources. Check your internet.", False

        with _lock:
            existing = _cache[mode]["hashes"] if mode in _cache else set()
            prev_nrm = _cache[mode]["nrm"]    if mode in _cache else None

        imp, nrm = _process(raw, mode, existing, prev_nrm)
        new_hashes = {a["hash"] for a in imp+nrm}
        is_new     = bool(new_hashes - existing)
        all_hashes = existing | new_hashes

        with _lock:
            _cache[mode] = {"ts":time.time(),"imp":imp,"nrm":nrm,"hashes":all_hashes}

        return imp, nrm, None, is_new
    except Exception as e:
        import traceback; traceback.print_exc()
        return [], [], f"Error: {e}", False

def get_global_news(force=False): return _get("global", force)
def get_india_news(force=False):  return _get("india",  force)
def clear_cache(mode=None):
    with _lock:
        if mode: _cache.pop(mode,None)
        else:    _cache.clear()